### ISSUE TITLE
redefinition of cDeviceComponentVersEntry

### ISSUE THREAD

**Issue by mauser2** [seanturner/draft-turner-ccmib#55]
Hello Sean,
i see these:

    cDeviceComponentVersEntry  OBJECT-TYPE
        SYNTAX      CDeviceComponentVersEntry
        MAX-ACCESS  not-accessible
        STATUS      current
  ....

    cDeviceComponentVersEntry  ::= SEQUENCE

smilint complaint aboue redefinition.

./CC-DEVICE-INFO-MIB:380: redefinition of identifier `cDeviceComponentVersEntry'
./CC-DEVICE-INFO-MIB:380: syntax error, unexpected COLON_COLON_EQUAL, expecting OBJECT
./CC-DEVICE-INFO-MIB:505: SMIv2 base type `Integer32' must be imported from SNMPv2-SMI
./CC-DEVICE-INFO-MIB:548: SMIv2 base type `Integer32' must be imported from SNMPv2-SMI
./CC-DEVICE-INFO-MIB:707: syntax error, unexpected LOWERCASE_IDENTIFIER, expecting COLON_COLON_EQUAL
./CC-DEVICE-INFO-MIB:664: type `RowStatus' of node `cFirmwareRowStatus' does not resolve to a known base type
./CC-DEVICE-INFO-MIB:360: unknown type `CDeviceComponentVersEntry'
./CC-DEVICE-INFO-MIB:617: unknown type `RowStatus'
[CC-DEVICE-INFO-MIB.txt](https://github.com/seanturner/draft-turner-ccmib/files/3424647/CC-DEVICE-INFO-MIB.txt)

**Comment by seanturner** [comment]
Thanks for this it should have been "cDeviceComponentVersEntry  ::= SEQUENCE".  Others will also land shortly.
